### ISSUE TITLE
RSS feed URLs broken

### ISSUE THREAD

**Issue by hughht5** [guyht/Glog#19]
On my Glog blog, the RSS feed links to www.example.com2012/09....
instead of www.example.com/2012/09...

Linked to this issue, the links are also not URL encoded causing broken links when the title has '%' or other special chars.

Is this a known issue? and are others having this problem? If so I can submit the fix I wrote for my glog.

**Comment by guyht** [comment]
Please submit the fix :)

**Comment by hughht5** [comment]
done :)

**Comment by guyht** [comment]
Where have you submitted it?

**Comment by hughht5** [comment]
I dunno - I'll try again in my lunch break....

Mr Hugh Halford-Thompson
+44 (0)7789231917 - UK mobile
hughht5@gmail.com

http://www.techcrunchlite.com/

4 Quilting Court
Garter Way
London SE16 6XF
UK

Le Grand Gennetay
49640 Morrannes
France

**Comment by hughht5** [comment]
Ok... I forgot to click submit!! lol. I've submitted a pull request.

hugh
