### ISSUE TITLE
Coffeescript?

### ISSUE THREAD

**Issue by wlaurance** [guyht/Glog#23]
Any chance you want to convert glog to coffee?

**Comment by guyht** [comment]
To be honest, I am not a big fan of Coffeescript.  I understand it has uses for people coming from a Ruby background, but imo, it can make debugging much harder, and, so long as you keep your JavaScript code nice and tidy, it does not add enough benefit to outweigh the cons.  Purely a personal opinion.

**Comment by wlaurance** [comment]
No prob. I use it for a lot of my projects but I have no ruby background. I think I just got tired of writing 'function' all the time. Using coffee will make it hard for all node people to contribute anyways.
