### ISSUE TITLE
No RSS or ATOM feed

### ISSUE THREAD

**Issue by unwiredben** [guyht/Glog#3]
Would really be great if you could add RSS 2.0 or Atom 1.0 output for the most recent 5 or 10 articles routed from index.xml or rss.xml and put a <meta> tag in the main page pointing to the feed.

**Comment by guyht** [comment]
Will add this to the roadmap.

**Comment by guyht** [comment]
@pinguxx has suggested using https://github.com/dylang/node-rss .  Assuming the library works as documented it should be a good fit.  Going to try to do the integration over the weekend.

**Comment by guyht** [comment]
RSS Feed added in 141a6a5abee10f95babe00304d5ea6dab1201b71 , using node-rss.

Please also merge changes from Guido https://github.com/guyht/Guido if you want RSS autodiscovery.

package.json has changed (node-rss added), so remember to do an 'npm install' after you have pulled the changes or Glog won't start.

G

**Comment by pinguxx** [comment]
working :)
