### ISSUE TITLE
Unclear License

### ISSUE THREAD

**Issue by jsoverson** [guyht/Glog#4]
The license indicates that the copyright is attributed to TJ Holowaychuk, not the owner of this repo "Guy Halford-Thompson" :

LICENSE:3: Copyright (c) 2009-2010 TJ Holowaychuk tj@vision-media.ca

Is this a derivative of something, or was the license file copied?

I concede that I may be missing something obvious but is not apparent to me right now.

**Comment by guyht** [comment]
Sorry, thats my fault for copying the MIT license file off one of TJ's projects.  I have updated the file so that I am the copyright holder.

Thanks for pointing it out.

G

**Comment by jsoverson** [comment]
5 minutes from open to close, I almost thought I was looking at my feed wrong. Thanks for the repo and addressing concerns :-)

**Comment by guyht** [comment]
No problem. I was actually at my computer when you posted the issue so wasnt too hard to get a fix in immediately. 

Thanks for your support

G
